In [1]:
!pip install imblearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting imblearn
  Downloading imblearn-0.0-py2.py3-none-any.whl (1.9 kB)
Requirement already satisfied: imbalanced-learn in /usr/local/lib/python3.10/dist-packages (from imblearn) (0.10.1)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.10/dist-packages (from imbalanced-learn->imblearn) (1.22.4)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.10/dist-packages (from imbalanced-learn->imblearn) (1.10.1)
Requirement already satisfied: scikit-learn>=1.0.2 in /usr/local/lib/python3.10/dist-packages (from imbalanced-learn->imblearn) (1.2.2)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from imbalanced-learn->imblearn) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from imbalanced-learn->imblearn) (3.1.0)
Installing collected packages: imblearn
Successfully installed imblearn-0.0

In [2]:
# import dependencies 
import numpy as np
import pandas as pd
from imblearn.over_sampling import RandomOverSampler
from pathlib import Path
from sklearn.metrics import balanced_accuracy_score, confusion_matrix, classification_report
import matplotlib.pyplot as plt

In [3]:
# Read the CSV file from the Resources folder into a Pandas DataFrame
oscars_df = pd.read_csv("oscars_df.csv")
# Review the DataFrame
pd.set_option('display.max_columns', None)
oscars_df

,Unnamed: 0,Film,Oscar Year,Film Studio/Producer(s),Award,Year of Release,Movie Time,Movie Genre,IMDB Rating,IMDB Votes,Movie Info,Genres,Critic Consensus,Content Rating,Directors,Authors,Actors,Original Release Date,Streaming Release Date,Production Company,Tomatometer Status,Tomatometer Rating,Tomatometer Count,Audience Status,Audience Rating,Audience Count,Tomatometer Top Critics Count,Tomatometer Fresh Critics Count,Tomatometer Rotten Critics Count,Film ID
0,0,Wings,1927/28,Famous Players-Lasky,Winner,1927,144,"Drama,Romance,War",7.5,"12,221","With World War I afoot, David Armstrong (Richa...","Action & Adventure, Classics",Subsequent war epics may have borrowed heavily...,PG-13,William Wellman,"Hope Loring, Louis D. Lighton","Clara Bow, Charles 'Buddy' Rogers, Richard Arl...",1927-08-12,2017-01-02,Unknown,Certified-Fresh,93.0,46.0,Upright,78.0,3530.0,9.0,43.0,3.0,2becf7d5-a3de-46ab-ae45-abdd6b588067
1,1,7th Heaven,1927/28,Fox,Nominee,1927,110,"Drama,Romance",7.7,"3,439",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19ed3295-a878-4fd2-8e60-5cd7b5f93dad
2,2,The Racket,1927/28,The Caddo Company,Nominee,1928,84,"Crime,Drama,Film-Noir",6.7,"1,257",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3111c2d8-0908-4093-8ff3-99c89f2f2f08
3,3,The Broadway Melody,1928/29,Metro-Goldwyn-Mayer,Winner,1929,100,"Drama,Musical,Romance",5.7,"6,890","Vaudeville sisters ""Hank"" (Bessie Love) and Qu...","Musical & Performing Arts, Romance",The Broadway Melody is interesting as an examp...,NR,Harry Beaumont,"James Gleason, Norman Houston, Sarah Y. Mason","Anita Page, Bessie Love, Charles King, Jed Pro...",1929-02-01,2017-02-25,MGM Home Entertainment,Rotten,33.0,24.0,Spilled,21.0,1813.0,7.0,8.0,16.0,de063f3f-2d35-4e1c-8636-6eb4c16bd236
4,4,Alibi,1928/29,Feature Productions,Nominee,1929,91,"Action,Crime,Romance",5.8,765,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,609887c2-877c-43a4-b88c-e40e31096a98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
566,566,Mank,2020,"Ce√°n Chaffin, Eric Roth, and Douglas Urbanski",Nominee,2020,131,"Biography,Comedy,Drama",6.9,"65,380",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47d4ae4f-e782-4cd9-9508-4a07302b1c1a
567,567,Minari,2020,Christina Oh,Nominee,2020,115,Drama,7.5,"57,976",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7262b3a8-214d-4205-985c-70e0860f3236
568,568,Promising Young Woman,2020,"Ben Browning, Ashley Fox, Emerald Fennell, and...",Nominee,2020,113,"Crime,Drama,Thriller",7.5,"122,269",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,d64c669b-7a73-496a-bddb-19cb09264371
569,569,Sound of Metal,2020,Bert Hamelinck and Sacha Ben Harroche,Nominee,2019,120,"Drama,Music",7.8,"102,807",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,647357e9-c067-46bd-aaeb-24d4344ec124
570,570,The Trial of the Chicago 7,2020,Marc Platt and Stuart M. Besser,Nominee,2020,129,"Drama,History,Thriller",7.8,"156,283",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,cecbca48-f19c-43f4-81d2-da130facda95

In [4]:
# drop unwanted columns
new_df=oscars_df.drop(columns=['Movie Info', 'Genres', 'Critic Consensus', 'Film ID', 'Audience Status', 'Tomatometer Status', 'Authors', 'Streaming Release Date', 'Original Release Date', 'Oscar Year', 'Tomatometer Rating','Tomatometer Count','Audience Rating','Audience Count','Tomatometer Top Critics Count','Tomatometer Fresh Critics Count','Tomatometer Rotten Critics Count'], axis=1)
new_df.tail(20)

,Unnamed: 0,Film,Film Studio/Producer(s),Award,Year of Release,Movie Time,Movie Genre,IMDB Rating,IMDB Votes,Content Rating,Directors,Actors,Production Company
551,551,Roma,Gabriela Rodr√≠guez and Alfonso Cuar√≥n,Nominee,2018,135,Drama,7.7,"147,705",R,Alfonso Cuar√≥n,"Yalitza Aparicio, Marina de Tavira, Diego Cort...",Netflix
552,552,A Star Is Born,"Bill Gerber, Bradley Cooper, and Lynette Howel...",Nominee,2018,136,"Drama,Music,Romance",7.6,"354,157",R,Bradley Cooper,"Lady Gaga, Bradley Cooper, Sam Elliott, Andrew...",Warner Bros. Pictures
553,553,Vice,"Dede Gardner, Jeremy Kleiner, Adam McKay, and ...",Nominee,2018,132,"Biography,Comdey,Drama",7.2,"132,014",R,Adam McKay,"Christian Bale, Amy Adams, Steve Carell, Sam R...",Annapurna Pictures
554,554,Parasite,Kwak Sin-ae and Bong Joon-ho,Winner,2019,132,"Comedy,Drama,Thriller",8.6,"651,517",NaN,NaN,NaN,NaN
555,555,1917,"Sam Mendes, Pippa Harris, Jayne-Ann Tenggren, ...",Nominee,2019,119,"Action,Drama,War",8.3,"485,648",NaN,NaN,NaN,NaN
556,556,Ford v Ferrari,"Peter Chernin, Jenno Topping, and James Mangold",Nominee,2019,152,"Action,Biography,Drama",8.1,"331,665",NaN,NaN,NaN,NaN
557,557,The Irishman,"Martin Scorsese, Robert De Niro, Jane Rosentha...",Nominee,2019,209,"Biography,Crime,Drama",7.8,"349,303",R,Martin Scorsese,"Robert De Niro, Al Pacino, Joe Pesci, Jesse Pl...",Netflix
558,558,Jojo Rabbit,"Carthew Neal, Taika Waititi, and Chelsea Winst...",Nominee,2019,108,"Comedy,Drama,War",7.9,"335,856",NaN,NaN,NaN,NaN
559,559,Joker,"Todd Phillips, Bradley Cooper, and Emma Tillin...",Nominee,2019,122,"Crime,Drama,Thriller",8.4,"1,056,051",R,Todd Phillips,"Joaquin Phoenix, Robert De Niro, Zazie Beetz, ...",Warner Bros. Pictures
560,560,Little Women,Amy Pascal,Nominee,2019,135,"Drama,Romance",7.8,"163,410",NaN,NaN,NaN,NaN
561,561,Marriage Story,Noah Baumbach and David Heyman,Nominee,2019,137,"Comedy,Drama,Romance",7.9,"270,304",R,Noah Baumbach,"Scarlett Johansson, Adam Driver, Laura Dern, A...",Netflix
562,562,Once Upon a Time in Hollywood,"David Heyman, Shannon McIntosh, and Quentin Ta...",Nominee,2019,161,"Comedy,Drama",7.6,"628,233",NaN,NaN,NaN,NaN
563,563,Nomadland,"Frances McDormand, Peter Spears, Mollye Asher,...",Nominee,2020,107,Drama,7.4,"123,041",NaN,NaN,NaN,NaN
564,564,The Father,"David Parfitt, Jean-Louis Livi, and Philippe C...",Nominee,2020,97,Drama,8.3,"89,693",NaN,NaN,NaN,NaN
565,565,Judas and the Black Messiah,"Shaka King, Charles D. King, and Ryan Coogler",Nominee,2021,126,"Biography,Drama,History",7.5,"58,996",NaN,NaN,NaN,NaN
566,566,Mank,"Ce√°n Chaffin, Eric Roth, and Douglas Urbanski",Nominee,2020,131,"Biography,Comedy,Drama",6.9,"65,380",NaN,NaN,NaN,NaN
567,567,Minari,Christina Oh,Nominee,2020,115,Drama,7.5,"57,976",NaN,NaN,NaN,NaN
568,568,Promising Young Woman,"Ben Browning, Ashley Fox, Emerald Fennell, and...",Nominee,2020,113,"Crime,Drama,Thriller",7.5,"122,269",NaN,NaN,NaN,NaN
569,569,Sound of Metal,Bert Hamelinck and Sacha Ben Harroche,Nominee,2019,120,"Drama,Music",7.8,"102,807",NaN,NaN,NaN,NaN
570,570,The Trial of the Chicago 7,Marc Platt and Stuart M. Besser,Nominee,2020,129,"Drama,History,Thriller",7.8,"156,283",NaN,NaN,NaN,NaN

In [5]:
# fill na with "unknown"
final_df=new_df.fillna("unknown")
final_df.head(20)

,Unnamed: 0,Film,Film Studio/Producer(s),Award,Year of Release,Movie Time,Movie Genre,IMDB Rating,IMDB Votes,Content Rating,Directors,Actors,Production Company
0,0,Wings,Famous Players-Lasky,Winner,1927,144,"Drama,Romance,War",7.5,"12,221",PG-13,William Wellman,"Clara Bow, Charles 'Buddy' Rogers, Richard Arl...",Unknown
1,1,7th Heaven,Fox,Nominee,1927,110,"Drama,Romance",7.7,"3,439",unknown,unknown,unknown,unknown
2,2,The Racket,The Caddo Company,Nominee,1928,84,"Crime,Drama,Film-Noir",6.7,"1,257",unknown,unknown,unknown,unknown
3,3,The Broadway Melody,Metro-Goldwyn-Mayer,Winner,1929,100,"Drama,Musical,Romance",5.7,"6,890",NR,Harry Beaumont,"Anita Page, Bessie Love, Charles King, Jed Pro...",MGM Home Entertainment
4,4,Alibi,Feature Productions,Nominee,1929,91,"Action,Crime,Romance",5.8,765,unknown,unknown,unknown,unknown
5,5,Hollywood Revue,Metro-Goldwyn-Mayer,Nominee,1929,130,"Comedy,Music",5.7,"2,004",unknown,unknown,unknown,unknown
6,6,In Old Arizona,Fox,Nominee,1928,95,Western,5.6,"1,019",NR,"Irving Cummings, Raoul Walsh","Warner Baxter, Edmund Lowe, Dorothy Burgess, J...",20th Century Fox Film Corporation
7,7,The Patriot,Paramount Famous Lasky,Nominee,1928,113,"Drama,History,Thriller",7.4,18,unknown,unknown,unknown,unknown
8,8,All Quiet on the Western Front,Universal,Winner,1930,152,"Drama,War",8.1,"59,214",unknown,unknown,unknown,unknown
9,9,The Big House,Cosmopolitan,Nominee,1930,87,"Crime,Drama,Thriller",7.1,"2,079",NR,George W. Hill,"Wallace Beery, Robert Montgomery, Chester Morr...",Warner Bros.
10,10,Disraeli,Warner Bros.,Nominee,1929,90,"Biography,Drama,History",6.2,"1,143",unknown,unknown,unknown,unknown
11,11,The Divorcee,Metro-Goldwyn-Mayer,Nominee,1930,84,"Romance,Drama",6.7,"2,982",unknown,unknown,unknown,unknown
12,12,The Love Parade,Paramount Famous Lasky,Nominee,1929,107,"Comedy,Musical,Romance",7.0,"2,163",unknown,unknown,unknown,unknown
13,13,Cimarron,RKO Radio,Winner,1931,123,"Drama,Western",5.9,"5,851",NR,Wesley Ruggles,"Richard Dix, Irene Dunne, Estelle Taylor, Nanc...",MGM Home Entertainment
14,14,East Lynne,Fox,Nominee,1931,102,"Drama,Romance",5.9,188,unknown,unknown,unknown,unknown
15,15,The Front Page,The Caddo Company,Nominee,1931,101,"Comedy,Crime,Drama",6.8,"2,741",unknown,unknown,unknown,unknown
16,16,Skippy,Paramount Publix,Nominee,1931,85,"Comedy,Drama,Family",6.3,772,unknown,unknown,unknown,unknown
17,17,Trader Horn,Metro-Goldwyn-Mayer,Nominee,1931,122,"Action,Adventure,Drama",6.3,957,unknown,unknown,unknown,unknown
18,18,Grand Hotel,Metro-Goldwyn-Mayer,Winner,1932,112,"Drama,Romance",7.4,"18,314",NR,Edmund Goulding,"Greta Garbo, John Barrymore, Joan Crawford, Wa...",MGM Home Entertainment
19,19,Arrowsmith,Samuel Goldwyn Productions,Nominee,1931,108,Drama,6.2,"1,663",unknown,unknown,unknown,unknown

In [6]:
# Count the number of null values in each column
null_counts = final_df.isnull().sum()
# Display the results
print(null_counts)

Unnamed: 0                 0
Film                       0
Film Studio/Producer(s)    0
Award                      0
Year of Release            0
Movie Time                 0
Movie Genre                0
IMDB Rating                0
IMDB Votes                 0
Content Rating             0
Directors                  0
Actors                     0
Production Company         0
dtype: int64

In [ ]:
# convert DataFrame to a csv file
# final_df.to_csv("cleaned_oscar_df.csv", index=False)

In [7]:
# Convert categorical data to numeric with `pd.get_dummies`
dummies_df=pd.get_dummies(final_df['Award'], dtype=float)
dummies_df.head()

   Nominee  Winner
0      0.0     1.0
1      1.0     0.0
2      1.0     0.0
3      0.0     1.0
4      1.0     0.0

In [8]:
# drop nominee column
is_winner=dummies_df.drop(["Nominee"], axis=1)
is_winner

     Winner
0       1.0
1       0.0
2       0.0
3       1.0
4       0.0
..      ...
566     0.0
567     0.0
568     0.0
569     0.0
570     0.0

[571 rows x 1 columns]

In [32]:
# Concatenate the original dataset with the dummy variables
df = pd.concat([final_df, is_winner], axis=1)
# Remove the original column if desired
df = df.drop('Award', axis=1)

df

,Unnamed: 0,Film,Film Studio/Producer(s),Year of Release,Movie Time,Movie Genre,IMDB Rating,IMDB Votes,Content Rating,Directors,Actors,Production Company,Winner
0,0,Wings,Famous Players-Lasky,1927,144,"Drama,Romance,War",7.5,"12,221",PG-13,William Wellman,"Clara Bow, Charles 'Buddy' Rogers, Richard Arl...",Unknown,1.0
1,1,7th Heaven,Fox,1927,110,"Drama,Romance",7.7,"3,439",unknown,unknown,unknown,unknown,0.0
2,2,The Racket,The Caddo Company,1928,84,"Crime,Drama,Film-Noir",6.7,"1,257",unknown,unknown,unknown,unknown,0.0
3,3,The Broadway Melody,Metro-Goldwyn-Mayer,1929,100,"Drama,Musical,Romance",5.7,"6,890",NR,Harry Beaumont,"Anita Page, Bessie Love, Charles King, Jed Pro...",MGM Home Entertainment,1.0
4,4,Alibi,Feature Productions,1929,91,"Action,Crime,Romance",5.8,765,unknown,unknown,unknown,unknown,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
566,566,Mank,"Ce√°n Chaffin, Eric Roth, and Douglas Urbanski",2020,131,"Biography,Comedy,Drama",6.9,"65,380",unknown,unknown,unknown,unknown,0.0
567,567,Minari,Christina Oh,2020,115,Drama,7.5,"57,976",unknown,unknown,unknown,unknown,0.0
568,568,Promising Young Woman,"Ben Browning, Ashley Fox, Emerald Fennell, and...",2020,113,"Crime,Drama,Thriller",7.5,"122,269",unknown,unknown,unknown,unknown,0.0
569,569,Sound of Metal,Bert Hamelinck and Sacha Ben Harroche,2019,120,"Drama,Music",7.8,"102,807",unknown,unknown,unknown,unknown,0.0
570,570,The Trial of the Chicago 7,Marc Platt and Stuart M. Besser,2020,129,"Drama,History,Thriller",7.8,"156,283",unknown,unknown,unknown,unknown,0.0

In [33]:
# spelling correction
df.iloc[[553]]=df.loc[df['Movie Genre']== 'Biography,Comdey,Drama'].replace('Biography,Comdey,Drama','Biography,Comedy,Drama')

In [34]:
# check to see if correction worked
df.iloc[[553]]

,Unnamed: 0,Film,Film Studio/Producer(s),Year of Release,Movie Time,Movie Genre,IMDB Rating,IMDB Votes,Content Rating,Directors,Actors,Production Company,Winner
553,553,Vice,"Dede Gardner, Jeremy Kleiner, Adam McKay, and ...",2018,132,"Biography,Comedy,Drama",7.2,"132,014",R,Adam McKay,"Christian Bale, Amy Adams, Steve Carell, Sam R...",Annapurna Pictures,0.0

In [35]:
# Get unique genres in the "Movie Genre" column
genres = df['Movie Genre'].unique()

# Print the unique genres
for genre in genres:
    print(genre)

Drama,Romance,War
Drama,Romance
Crime,Drama,Film-Noir
Drama,Musical,Romance
Action,Crime,Romance
Comedy,Music
Western
Drama,History,Thriller
Drama,War
Crime,Drama,Thriller
Biography,Drama,History
Romance,Drama
Comedy,Musical,Romance
Drama,Western
Comedy,Crime,Drama
Comedy,Drama,Family
Action,Adventure,Drama
Drama
Drama,Sport
Crime,Drama
Adventure,Drama,Romance
Comedy,Romance,Musical
Comedy,Drama,Musical
Comedy,Drama
Drama,Family,Romance
Biography,Comedy,Drama
Comedy,Drama,History
Comedy,Drama,Romance
Comedy,Romance
Biography,Drama,Romance
Musical,Romance
Music,Romance
Comedy,Crime,Mystery
Action,Biography,Romance
Adventure,Biography,Drama
Action,Adventure,History
Adventure,Drama,War
Comedy,Fantasy,Romance
Drama,History,Romance
Comedy,Romance,Western
Biography,Drama,Musical
Biography,Drama
Adventure,Drama,Family
Action,Drama,Musical
Adventure,Drama,Fantasy
Comedy,Drama,Music
Action,Adventure,Romance
Drama,Music,Musical
Drama,Music,Romance
Adventure,Drama
Adventure,Drama,Western
Adventure,Family,Fantasy
Drama,Mystery,Romance
Action,Romance,Thriller
Drama,History
Comedy,Drama,War
Drama,Family
Drama,Mystery
Crime,Film-Noir,Mystery
Film-Noir,Mystery,Thriller
Drama,Thriller,War
Action,Drama,War
Biography,Drama,Music
Adventure,Drama,History
Comedy,Drama,Fantasy
Comedy,Romance,War
Drama,Thriller
Crime,Drama,Mystery
Drama,Film-Noir
Comedy,Fantasy,Music
Film-Noir,Mystery,Romance
Drama,Family,Fantasy
Drama,Family,Western
Adventure,Drama,Mystery
Action,Drama,History
Drama,Thriller,Western
Drama,Music
Adventure,Comedy,Family
Biography,Drama,Family
Crime,Drama,Musical
Comedy,Family,Musical
Adventure,Comedy,History
Drama,Family,Musical
Comedy
Comedy,Family,Fantasy
Comedy,War
Action,Biography,Crime
Biography,Crime,Drama
Adventure,Comedy,Musical
Crime,Drama,History
Biography,Drama,War
Action,Drama,Thriller
Action,Crime,Drama
Crime,Drama,Sci-Fi
Adventure,Drama,Thriller
Horror
Drama,Mystery,Thriller
Adventure,Thriller
Action,Adventure,Fantasy
Drama,Mystery,War
Biography,Drama,Sport
Crime,Drama,Romance
Action,Adventure
Horror,Mystery,Thriller
Family,Sci-Fi
Drama,Fantasy,Romance
Animation,Family,Fantasy
Crime,Drama,Fantasy
Biography,Drama,Thriller
Comedy,Drama,Mystery
Comedy,Crime,Musical
Drama,History,Sport
Action,Sci-Fi,Thriller
Animation,Adventure,Comedy
Action,Adventure,Sci-Fi
Drama,Fantasy
Drama,History,Musical
Adventure,Biography,Crime
Drama,Sci-Fi,Thriller
Drama,Romance,Sci-Fi
Adventure,Comedy,Drama
Action,Biography,Drama
Adventure,Comedy,Crime
Adventure,Drama,Sci-Fi
Drama,Sci-Fi
Biography,Comedy,Crime
Comedy,Drama,Thriller

In [36]:
# split movie genre on the comma
unique_genres=set(''.join(df['Movie Genre']).split(','))
unique_genres=list(unique_genres)
unique_genres

['DramaDramaDramaBiography',
 'DramaDrama',
 'Comedy',
 'Film-Noir',
 'Drama',
 'SportAction',
 'RomanceDramaAction',
 'DramaAdventure',
 'WarBiography',
 'FantasyCrime',
 'WesternComedy',
 'MusicDrama',
 'ThrillerBiography',
 'DramaDramaDrama',
 'RomanceComedy',
 'RomanceDramaAdventure',
 'HistoryDramaCrime',
 'WarDramaDrama',
 'FamilyCrime',
 'Music',
 'ThrillerDramaDrama',
 'Sci-FiDramaBiography',
 'DramaAnimation',
 'Sci-FiDrama',
 'Musical',
 'Film-NoirAdventure',
 'MysteryDrama',
 'Sci-FiAction',
 'DramaAction',
 'RomanceDramaBiography',
 'HistoryDrama',
 'Sci-Fi',
 'MusicalBiography',
 'WarComedy',
 'FamilyAction',
 'CrimeAdventure',
 'FamilyBiography',
 'ThrillerComedy',
 'MysteryBiography',
 'MusicWesternDrama',
 'MysteryComedy',
 'Family',
 'HistoryRomance',
 'Romance',
 'SportDrama',
 'ComedyComedy',
 'MusicalDrama',
 'WarDrama',
 'ThrillerDrama',
 'WesternBiography',
 'RomanceDramaDrama',
 'MusicBiography',
 'WarAdventure',
 'Mystery',
 'HistoryBiography',
 'Fantasy',
 'DramaComedy',
 'MysteryCrime',
 'HistoryComedy',
 'WesternAdventure',
 'WarAction',
 'Biography',
 'FamilyDramaDrama',
 'HistoryFamily',
 'ComedyDrama',
 'HistoryMusical',
 'Thriller',
 'RomanceAction',
 'HistoryAdventure',
 'MusicalAdventure',
 'WarDramaComedy',
 'FantasyDrama',
 'FantasyAction',
 'RomanceDramaDramaComedy',
 'MusicCrime',
 'DramaBiography',
 'HistoryDramaDrama',
 'SportBiography',
 'Adventure',
 'ThrillerAnimation',
 'RomanceMusic',
 'WesternCrime',
 'Sci-FiAdventure',
 'HistoryCrime',
 'MusicAction',
 'ThrillerDramaAction',
 'DramaDramaAdventure',
 'HistoryDramaBiography',
 'FamilyComedy',
 'RomanceDramaComedy',
 'RomanceDramaDramaBiography',
 'Film-NoirDrama',
 'Film-NoirComedy',
 'WarCrime',
 'RomanceCrime',
 'Crime',
 'FantasyBiography',
 'RomanceBiography',
 'Film-NoirAction',
 'MusicalCrime',
 'DramaDramaHorrorComedy',
 'FamilyDramaDramaDrama',
 'AdventureHorror',
 'HistoryDramaDramaAdventure',
 'CrimeBiography',
 'Film-NoirFilm-Noir',
 'DramaDramaCrime',
 'MysteryAction',
 'FamilyDrama',
 'MysteryDramaDrama',
 'RomanceDramaCrime',
 'WesternDrama',
 'Sci-FiComedy',
 'HistoryFilm-Noir',
 'RomanceAdventure',
 'RomanceDrama',
 'MysteryAdventure',
 'History',
 'ThrillerAction',
 'MusicDramaCrime',
 'DramaCrime',
 'Sci-FiBiography',
 'MusicalComedy',
 'RomanceMusical',
 'FantasyComedy',
 'ThrillerDramaAdventure',
 'SportCrime',
 'HistoryComedyComedy',
 'MusicComedy',
 'HistoryWesternDramaDrama',
 'HistoryAction',
 'HistoryHorror',
 'Film-NoirCrime']

In [37]:
good_genres=[genre for genre in unique_genres if not '-' in genre]
good_genres

['DramaDramaDramaBiography',
 'DramaDrama',
 'Comedy',
 'Drama',
 'SportAction',
 'RomanceDramaAction',
 'DramaAdventure',
 'WarBiography',
 'FantasyCrime',
 'WesternComedy',
 'MusicDrama',
 'ThrillerBiography',
 'DramaDramaDrama',
 'RomanceComedy',
 'RomanceDramaAdventure',
 'HistoryDramaCrime',
 'WarDramaDrama',
 'FamilyCrime',
 'Music',
 'ThrillerDramaDrama',
 'DramaAnimation',
 'Musical',
 'MysteryDrama',
 'DramaAction',
 'RomanceDramaBiography',
 'HistoryDrama',
 'MusicalBiography',
 'WarComedy',
 'FamilyAction',
 'CrimeAdventure',
 'FamilyBiography',
 'ThrillerComedy',
 'MysteryBiography',
 'MusicWesternDrama',
 'MysteryComedy',
 'Family',
 'HistoryRomance',
 'Romance',
 'SportDrama',
 'ComedyComedy',
 'MusicalDrama',
 'WarDrama',
 'ThrillerDrama',
 'WesternBiography',
 'RomanceDramaDrama',
 'MusicBiography',
 'WarAdventure',
 'Mystery',
 'HistoryBiography',
 'Fantasy',
 'DramaComedy',
 'MysteryCrime',
 'HistoryComedy',
 'WesternAdventure',
 'WarAction',
 'Biography',
 'FamilyDramaDrama',
 'HistoryFamily',
 'ComedyDrama',
 'HistoryMusical',
 'Thriller',
 'RomanceAction',
 'HistoryAdventure',
 'MusicalAdventure',
 'WarDramaComedy',
 'FantasyDrama',
 'FantasyAction',
 'RomanceDramaDramaComedy',
 'MusicCrime',
 'DramaBiography',
 'HistoryDramaDrama',
 'SportBiography',
 'Adventure',
 'ThrillerAnimation',
 'RomanceMusic',
 'WesternCrime',
 'HistoryCrime',
 'MusicAction',
 'ThrillerDramaAction',
 'DramaDramaAdventure',
 'HistoryDramaBiography',
 'FamilyComedy',
 'RomanceDramaComedy',
 'RomanceDramaDramaBiography',
 'WarCrime',
 'RomanceCrime',
 'Crime',
 'FantasyBiography',
 'RomanceBiography',
 'MusicalCrime',
 'DramaDramaHorrorComedy',
 'FamilyDramaDramaDrama',
 'AdventureHorror',
 'HistoryDramaDramaAdventure',
 'CrimeBiography',
 'DramaDramaCrime',
 'MysteryAction',
 'FamilyDrama',
 'MysteryDramaDrama',
 'RomanceDramaCrime',
 'WesternDrama',
 'RomanceAdventure',
 'RomanceDrama',
 'MysteryAdventure',
 'History',
 'ThrillerAction',
 'MusicDramaCrime',
 'DramaCrime',
 'MusicalComedy',
 'RomanceMusical',
 'FantasyComedy',
 'ThrillerDramaAdventure',
 'SportCrime',
 'HistoryComedyComedy',
 'MusicComedy',
 'HistoryWesternDramaDrama',
 'HistoryAction',
 'HistoryHorror']

In [38]:
bad_genres=[genre.replace('-F', '-f').replace('-N', '-n') for genre in unique_genres if '-' in genre]
bad_genres

['Film-noir',
 'Sci-fiDramaBiography',
 'Sci-fiDrama',
 'Film-noirAdventure',
 'Sci-fiAction',
 'Sci-fi',
 'Sci-fiAdventure',
 'Film-noirDrama',
 'Film-noirComedy',
 'Film-noirAction',
 'Film-noirFilm-noir',
 'Sci-fiComedy',
 'HistoryFilm-noir',
 'Sci-fiBiography',
 'Film-noirCrime']

In [39]:
unique_genres=good_genres+bad_genres
unique_genres

['DramaDramaDramaBiography',
 'DramaDrama',
 'Comedy',
 'Drama',
 'SportAction',
 'RomanceDramaAction',
 'DramaAdventure',
 'WarBiography',
 'FantasyCrime',
 'WesternComedy',
 'MusicDrama',
 'ThrillerBiography',
 'DramaDramaDrama',
 'RomanceComedy',
 'RomanceDramaAdventure',
 'HistoryDramaCrime',
 'WarDramaDrama',
 'FamilyCrime',
 'Music',
 'ThrillerDramaDrama',
 'DramaAnimation',
 'Musical',
 'MysteryDrama',
 'DramaAction',
 'RomanceDramaBiography',
 'HistoryDrama',
 'MusicalBiography',
 'WarComedy',
 'FamilyAction',
 'CrimeAdventure',
 'FamilyBiography',
 'ThrillerComedy',
 'MysteryBiography',
 'MusicWesternDrama',
 'MysteryComedy',
 'Family',
 'HistoryRomance',
 'Romance',
 'SportDrama',
 'ComedyComedy',
 'MusicalDrama',
 'WarDrama',
 'ThrillerDrama',
 'WesternBiography',
 'RomanceDramaDrama',
 'MusicBiography',
 'WarAdventure',
 'Mystery',
 'HistoryBiography',
 'Fantasy',
 'DramaComedy',
 'MysteryCrime',
 'HistoryComedy',
 'WesternAdventure',
 'WarAction',
 'Biography',
 'FamilyDramaDrama',
 'HistoryFamily',
 'ComedyDrama',
 'HistoryMusical',
 'Thriller',
 'RomanceAction',
 'HistoryAdventure',
 'MusicalAdventure',
 'WarDramaComedy',
 'FantasyDrama',
 'FantasyAction',
 'RomanceDramaDramaComedy',
 'MusicCrime',
 'DramaBiography',
 'HistoryDramaDrama',
 'SportBiography',
 'Adventure',
 'ThrillerAnimation',
 'RomanceMusic',
 'WesternCrime',
 'HistoryCrime',
 'MusicAction',
 'ThrillerDramaAction',
 'DramaDramaAdventure',
 'HistoryDramaBiography',
 'FamilyComedy',
 'RomanceDramaComedy',
 'RomanceDramaDramaBiography',
 'WarCrime',
 'RomanceCrime',
 'Crime',
 'FantasyBiography',
 'RomanceBiography',
 'MusicalCrime',
 'DramaDramaHorrorComedy',
 'FamilyDramaDramaDrama',
 'AdventureHorror',
 'HistoryDramaDramaAdventure',
 'CrimeBiography',
 'DramaDramaCrime',
 'MysteryAction',
 'FamilyDrama',
 'MysteryDramaDrama',
 'RomanceDramaCrime',
 'WesternDrama',
 'RomanceAdventure',
 'RomanceDrama',
 'MysteryAdventure',
 'History',
 'ThrillerAction',
 'MusicDramaCrime',
 'DramaCrime',
 'MusicalComedy',
 'RomanceMusical',
 'FantasyComedy',
 'ThrillerDramaAdventure',
 'SportCrime',
 'HistoryComedyComedy',
 'MusicComedy',
 'HistoryWesternDramaDrama',
 'HistoryAction',
 'HistoryHorror',
 'Film-noir',
 'Sci-fiDramaBiography',
 'Sci-fiDrama',
 'Film-noirAdventure',
 'Sci-fiAction',
 'Sci-fi',
 'Sci-fiAdventure',
 'Film-noirDrama',
 'Film-noirComedy',
 'Film-noirAction',
 'Film-noirFilm-noir',
 'Sci-fiComedy',
 'HistoryFilm-noir',
 'Sci-fiBiography',
 'Film-noirCrime']

In [40]:
unique_genres

['DramaDramaDramaBiography',
 'DramaDrama',
 'Comedy',
 'Drama',
 'SportAction',
 'RomanceDramaAction',
 'DramaAdventure',
 'WarBiography',
 'FantasyCrime',
 'WesternComedy',
 'MusicDrama',
 'ThrillerBiography',
 'DramaDramaDrama',
 'RomanceComedy',
 'RomanceDramaAdventure',
 'HistoryDramaCrime',
 'WarDramaDrama',
 'FamilyCrime',
 'Music',
 'ThrillerDramaDrama',
 'DramaAnimation',
 'Musical',
 'MysteryDrama',
 'DramaAction',
 'RomanceDramaBiography',
 'HistoryDrama',
 'MusicalBiography',
 'WarComedy',
 'FamilyAction',
 'CrimeAdventure',
 'FamilyBiography',
 'ThrillerComedy',
 'MysteryBiography',
 'MusicWesternDrama',
 'MysteryComedy',
 'Family',
 'HistoryRomance',
 'Romance',
 'SportDrama',
 'ComedyComedy',
 'MusicalDrama',
 'WarDrama',
 'ThrillerDrama',
 'WesternBiography',
 'RomanceDramaDrama',
 'MusicBiography',
 'WarAdventure',
 'Mystery',
 'HistoryBiography',
 'Fantasy',
 'DramaComedy',
 'MysteryCrime',
 'HistoryComedy',
 'WesternAdventure',
 'WarAction',
 'Biography',
 'FamilyDramaDrama',
 'HistoryFamily',
 'ComedyDrama',
 'HistoryMusical',
 'Thriller',
 'RomanceAction',
 'HistoryAdventure',
 'MusicalAdventure',
 'WarDramaComedy',
 'FantasyDrama',
 'FantasyAction',
 'RomanceDramaDramaComedy',
 'MusicCrime',
 'DramaBiography',
 'HistoryDramaDrama',
 'SportBiography',
 'Adventure',
 'ThrillerAnimation',
 'RomanceMusic',
 'WesternCrime',
 'HistoryCrime',
 'MusicAction',
 'ThrillerDramaAction',
 'DramaDramaAdventure',
 'HistoryDramaBiography',
 'FamilyComedy',
 'RomanceDramaComedy',
 'RomanceDramaDramaBiography',
 'WarCrime',
 'RomanceCrime',
 'Crime',
 'FantasyBiography',
 'RomanceBiography',
 'MusicalCrime',
 'DramaDramaHorrorComedy',
 'FamilyDramaDramaDrama',
 'AdventureHorror',
 'HistoryDramaDramaAdventure',
 'CrimeBiography',
 'DramaDramaCrime',
 'MysteryAction',
 'FamilyDrama',
 'MysteryDramaDrama',
 'RomanceDramaCrime',
 'WesternDrama',
 'RomanceAdventure',
 'RomanceDrama',
 'MysteryAdventure',
 'History',
 'ThrillerAction',
 'MusicDramaCrime',
 'DramaCrime',
 'MusicalComedy',
 'RomanceMusical',
 'FantasyComedy',
 'ThrillerDramaAdventure',
 'SportCrime',
 'HistoryComedyComedy',
 'MusicComedy',
 'HistoryWesternDramaDrama',
 'HistoryAction',
 'HistoryHorror',
 'Film-noir',
 'Sci-fiDramaBiography',
 'Sci-fiDrama',
 'Film-noirAdventure',
 'Sci-fiAction',
 'Sci-fi',
 'Sci-fiAdventure',
 'Film-noirDrama',
 'Film-noirComedy',
 'Film-noirAction',
 'Film-noirFilm-noir',
 'Sci-fiComedy',
 'HistoryFilm-noir',
 'Sci-fiBiography',
 'Film-noirCrime']

In [41]:
import re

container=[]

for each_genre in unique_genres: 
  ini_str=each_genre
  res_list = [s for s in re.split("([A-Z][^A-Z]*)", ini_str) if s]
  container=container+res_list

In [42]:
container

['Drama',
 'Drama',
 'Drama',
 'Biography',
 'Drama',
 'Drama',
 'Comedy',
 'Drama',
 'Sport',
 'Action',
 'Romance',
 'Drama',
 'Action',
 'Drama',
 'Adventure',
 'War',
 'Biography',
 'Fantasy',
 'Crime',
 'Western',
 'Comedy',
 'Music',
 'Drama',
 'Thriller',
 'Biography',
 'Drama',
 'Drama',
 'Drama',
 'Romance',
 'Comedy',
 'Romance',
 'Drama',
 'Adventure',
 'History',
 'Drama',
 'Crime',
 'War',
 'Drama',
 'Drama',
 'Family',
 'Crime',
 'Music',
 'Thriller',
 'Drama',
 'Drama',
 'Drama',
 'Animation',
 'Musical',
 'Mystery',
 'Drama',
 'Drama',
 'Action',
 'Romance',
 'Drama',
 'Biography',
 'History',
 'Drama',
 'Musical',
 'Biography',
 'War',
 'Comedy',
 'Family',
 'Action',
 'Crime',
 'Adventure',
 'Family',
 'Biography',
 'Thriller',
 'Comedy',
 'Mystery',
 'Biography',
 'Music',
 'Western',
 'Drama',
 'Mystery',
 'Comedy',
 'Family',
 'History',
 'Romance',
 'Romance',
 'Sport',
 'Drama',
 'Comedy',
 'Comedy',
 'Musical',
 'Drama',
 'War',
 'Drama',
 'Thriller',
 'Drama',
 'Western',
 'Biography',
 'Romance',
 'Drama',
 'Drama',
 'Music',
 'Biography',
 'War',
 'Adventure',
 'Mystery',
 'History',
 'Biography',
 'Fantasy',
 'Drama',
 'Comedy',
 'Mystery',
 'Crime',
 'History',
 'Comedy',
 'Western',
 'Adventure',
 'War',
 'Action',
 'Biography',
 'Family',
 'Drama',
 'Drama',
 'History',
 'Family',
 'Comedy',
 'Drama',
 'History',
 'Musical',
 'Thriller',
 'Romance',
 'Action',
 'History',
 'Adventure',
 'Musical',
 'Adventure',
 'War',
 'Drama',
 'Comedy',
 'Fantasy',
 'Drama',
 'Fantasy',
 'Action',
 'Romance',
 'Drama',
 'Drama',
 'Comedy',
 'Music',
 'Crime',
 'Drama',
 'Biography',
 'History',
 'Drama',
 'Drama',
 'Sport',
 'Biography',
 'Adventure',
 'Thriller',
 'Animation',
 'Romance',
 'Music',
 'Western',
 'Crime',
 'History',
 'Crime',
 'Music',
 'Action',
 'Thriller',
 'Drama',
 'Action',
 'Drama',
 'Drama',
 'Adventure',
 'History',
 'Drama',
 'Biography',
 'Family',
 'Comedy',
 'Romance',
 'Drama',
 'Comedy',
 'Romance',
 'Drama',
 'Drama',
 'Biography',
 'War',
 'Crime',
 'Romance',
 'Crime',
 'Crime',
 'Fantasy',
 'Biography',
 'Romance',
 'Biography',
 'Musical',
 'Crime',
 'Drama',
 'Drama',
 'Horror',
 'Comedy',
 'Family',
 'Drama',
 'Drama',
 'Drama',
 'Adventure',
 'Horror',
 'History',
 'Drama',
 'Drama',
 'Adventure',
 'Crime',
 'Biography',
 'Drama',
 'Drama',
 'Crime',
 'Mystery',
 'Action',
 'Family',
 'Drama',
 'Mystery',
 'Drama',
 'Drama',
 'Romance',
 'Drama',
 'Crime',
 'Western',
 'Drama',
 'Romance',
 'Adventure',
 'Romance',
 'Drama',
 'Mystery',
 'Adventure',
 'History',
 'Thriller',
 'Action',
 'Music',
 'Drama',
 'Crime',
 'Drama',
 'Crime',
 'Musical',
 'Comedy',
 'Romance',
 'Musical',
 'Fantasy',
 'Comedy',
 'Thriller',
 'Drama',
 'Adventure',
 'Sport',
 'Crime',
 'History',
 'Comedy',
 'Comedy',
 'Music',
 'Comedy',
 'History',
 'Western',
 'Drama',
 'Drama',
 'History',
 'Action',
 'History',
 'Horror',
 'Film-noir',
 'Sci-fi',
 'Drama',
 'Biography',
 'Sci-fi',
 'Drama',
 'Film-noir',
 'Adventure',
 'Sci-fi',
 'Action',
 'Sci-fi',
 'Sci-fi',
 'Adventure',
 'Film-noir',
 'Drama',
 'Film-noir',
 'Comedy',
 'Film-noir',
 'Action',
 'Film-noir',
 'Film-noir',
 'Sci-fi',
 'Comedy',
 'History',
 'Film-noir',
 'Sci-fi',
 'Biography',
 'Film-noir',
 'Crime']

In [43]:
tiny_genres=list(set(container))
tiny_genres.remove('Sci-fi')
tiny_genres.remove('Film-noir')
tiny_genres.append('Sci-Fi')
tiny_genres.append('Film-Noir')
tiny_genres

['Comedy',
 'Drama',
 'Sport',
 'Western',
 'Thriller',
 'War',
 'Family',
 'Romance',
 'Adventure',
 'Music',
 'History',
 'Musical',
 'Action',
 'Animation',
 'Mystery',
 'Horror',
 'Crime',
 'Fantasy',
 'Biography',
 'Sci-Fi',
 'Film-Noir']

In [44]:
big_list=[]
for idx, genre_long_str in df['Movie Genre'].iteritems():
  encoded=[]
  for each_genre in tiny_genres: 
    if each_genre in genre_long_str: 
      encoded.append(1)
    else: 
      encoded.append(0)
  big_list.append(encoded)

<ipython-input-44-0ee5aa898908>:2: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for idx, genre_long_str in df['Movie Genre'].iteritems():

In [45]:
df['Movie Genre'].head()

0        Drama,Romance,War
1            Drama,Romance
2    Crime,Drama,Film-Noir
3    Drama,Musical,Romance
4     Action,Crime,Romance
Name: Movie Genre, dtype: object

In [46]:
genre_df=pd.DataFrame(big_list, columns=tiny_genres)
genre_df.head()

,Comedy,Drama,Sport,Western,Thriller,War,Family,Romance,Adventure,Music,History,Musical,Action,Animation,Mystery,Horror,Crime,Fantasy,Biography,Sci-Fi,Film-Noir
0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1
3,0,1,0,0,0,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0

In [48]:
# Concatenate the original dataset with the dummy variables
concat_df = pd.concat([df, genre_df], axis=1)
# Remove the original column if desired
concat_df = concat_df.drop('Movie Genre', axis=1)

concat_df

,Unnamed: 0,Film,Film Studio/Producer(s),Year of Release,Movie Time,IMDB Rating,IMDB Votes,Content Rating,Directors,Actors,Production Company,Winner,Comedy,Drama,Sport,Western,Thriller,War,Family,Romance,Adventure,Music,History,Musical,Action,Animation,Mystery,Horror,Crime,Fantasy,Biography,Sci-Fi,Film-Noir
0,0,Wings,Famous Players-Lasky,1927,144,7.5,"12,221",PG-13,William Wellman,"Clara Bow, Charles 'Buddy' Rogers, Richard Arl...",Unknown,1.0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1,7th Heaven,Fox,1927,110,7.7,"3,439",unknown,unknown,unknown,unknown,0.0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
2,2,The Racket,The Caddo Company,1928,84,6.7,"1,257",unknown,unknown,unknown,unknown,0.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1
3,3,The Broadway Melody,Metro-Goldwyn-Mayer,1929,100,5.7,"6,890",NR,Harry Beaumont,"Anita Page, Bessie Love, Charles King, Jed Pro...",MGM Home Entertainment,1.0,0,1,0,0,0,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0
4,4,Alibi,Feature Productions,1929,91,5.8,765,unknown,unknown,unknown,unknown,0.0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
566,566,Mank,"Ce√°n Chaffin, Eric Roth, and Douglas Urbanski",2020,131,6.9,"65,380",unknown,unknown,unknown,unknown,0.0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
567,567,Minari,Christina Oh,2020,115,7.5,"57,976",unknown,unknown,unknown,unknown,0.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
568,568,Promising Young Woman,"Ben Browning, Ashley Fox, Emerald Fennell, and...",2020,113,7.5,"122,269",unknown,unknown,unknown,unknown,0.0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
569,569,Sound of Metal,Bert Hamelinck and Sacha Ben Harroche,2019,120,7.8,"102,807",unknown,unknown,unknown,unknown,0.0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
570,570,The Trial of the Chicago 7,Marc Platt and Stuart M. Besser,2020,129,7.8,"156,283",unknown,unknown,unknown,unknown,0.0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0

In [ ]:
# Use the `StandardScaler()` module from scikit-learn to normalize the data from the CSV file
#scaled_data = StandardScaler().fit_transform(df_market_data)
# Diplay the first five rows of the scaled data to confirm normalization
#scaled_data[0:5]

In [ ]:
# weighted avg rating for each director
# group (some metric that reps director) by director and find average